FROM node:18-alpine as build

WORKDIR /app

COPY myclient/package*.json ./

RUN npm install --legacy-peer-deps

COPY myclient/ ./

RUN npm run build --legacy-peer-deps

# 生产环境
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 