FROM mysql:8.0

# 添加数据库初始化脚本
COPY server/db/init.sql /docker-entrypoint-initdb.d/

# 添加权限设置脚本

# 添加MySQL配置
COPY mysql-config.cnf /etc/mysql/conf.d/

# 通过ARG而不是ENV设置默认值，实际值将通过docker run命令传入
ARG MYSQL_ROOT_PASSWORD_DEFAULT=rootpassword
ARG MYSQL_DATABASE_DEFAULT=crm_system
ARG MYSQL_USER_DEFAULT=root
ARG MYSQL_PASSWORD_DEFAULT=root

# 设置字符集和排序规则
CMD ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

EXPOSE 3306 