version: '3.8'

services:
  frontend:
    build:
      context: ./myclient
      dockerfile: Dockerfile
    container_name: ycsolar-frontend
    ports:
      - "3000:3000"
    networks:
      - ycsolar-network
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ycsolar-backend
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=crm_system
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    networks:
      - ycsolar-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ycsolar-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crm_system
      - MYSQL_PASSWORD=root
    networks:
      - ycsolar-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ycsolar-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - ycsolar-network
    restart: unless-stopped

networks:
  ycsolar-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  uploads:
    driver: local 