version: '3.8'

services:
  frontend:
    image: leileigwl/ycsolar-frontend:1.1.2
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: ycsolar-frontend
    ports:
      - "3000:3000"
    networks:
      - ycsolar-network
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  backend:
    image: leileigwl/ycsolar-backend:1.1.2
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: ycsolar-backend
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=crm_system
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    networks:
      - ycsolar-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: leileigwl/ycsolar-db:1.1.2
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: ycsolar-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crm_system
      - MYSQL_PASSWORD=root
    networks:
      - ycsolar-network
    restart: unless-stopped

networks:
  ycsolar-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  uploads:
    driver: local 
