version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=db
      - DB_USER=ycuser
      - DB_PASSWORD=ycpassword
      - DB_NAME=ycsolar
      - JWT_SECRET=your_jwt_secret_key_here
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ycsolar
      - MYSQL_USER=ycuser
      - MYSQL_PASSWORD=ycpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 