FROM node:18-alpine

WORKDIR /app

# 设置npm使用淘宝镜像
RUN npm config set registry https://registry.npmmirror.com

# 添加构建依赖项
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update && apk add --no-cache python3 make g++ gcc

COPY server/package*.json ./

# 安装依赖并清理npm缓存以减少镜像大小
RUN npm install --no-audit && npm cache clean --force

COPY server/ ./

# 创建上传目录
RUN mkdir -p uploads && chmod 777 uploads

EXPOSE 5000

CMD ["npm", "start"] 